import os
import datetime

def generate_daily_briefing(analysis_text, all_data):
    """
    エドワード・タフテ & デイヴィッド・オグルヴィ（The Publisher）。
    ニュースと分析結果を美しいMarkdown形式のデイリーレポートとして生成する。
    ダッシュボードで読み込みやすい形式（カードUI等）を想定したマークダウン。
    """
    date_str = datetime.datetime.now().strftime("%Y-%m-%d")
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
    report_filename = os.path.join(base_dir, 'reports', 'daily_briefings', f'Briefing_{date_str}.md')

    rate = all_data.get('exchange_rate', {}).get('twd_to_jpy', 'N/A')

    content = f"# 🚀 Antigravity Daily Executive Briefing\n"
    content += f"**Date**: {date_str} | **To**: The Chairman (User)\n"
    content += f"**Generated by**: The Autonomous Office (Phase 11)\n\n"
    content += f"---\n\n"

    # 1. 経済・為替インジケーター
    content += f"## 📈 1. Economic Indicators\n"
    content += f"> **Exchange Rate (TWD/JPY)**: 1 TWD = **{rate} JPY**\n\n"

    # helper関数: ニュースリストのフォーマット
    def format_news_section(title, icon, news_list):
        sec = f"## {icon} {title}\n"
        if not news_list:
            sec += "*No Data*\n\n"
            return sec
        for item in news_list:
            sec += f"### [{item['title']}]({item['link']})\n"
            summary_lines = str(item['summary']).strip().split('\n')
            for line in summary_lines:
                if line.strip() == "":
                    sec += f">\n"
                else:
                    sec += f"> {line.strip()}\n"
            sec += "\n"
        sec += "---\n\n"
        return sec

    # 2. ニュースダイジェスト
    content += format_news_section("Google AI & Antigravity Intelligence", "🧠", all_data.get('ai_news', []))
    content += format_news_section("Japan Top News", "🇯🇵", all_data.get('japan_news', []))
    content += format_news_section("Taiwan & China Relations", "🇹🇼", all_data.get('taiwan_news', []))
    content += format_news_section("Global Tech Trends", "💻", all_data.get('tech_news', []))

    content += f"---\n\n"

    # 3. マルチエージェント分析
    content += f"## 🧑‍💻 3. Multi-Agent Strategic Analysis\n"
    content += f"我々Antigravityの専門家陣によるディベート結果・アクションプラン体系化：\n\n"
    content += f"{analysis_text}\n\n"

    content += f"---\n"
    content += f"*End of Report. Ready for The Dashboard UI rendering.*\n"

    # ファイル書き込み
    os.makedirs(os.path.dirname(report_filename), exist_ok=True)
    with open(report_filename, "w", encoding="utf-8") as f:
        f.write(content)

    return report_filename
